export interface InformeInterface{
    comprobable:    number,
    incorrecto:     number,
    inequivoco:     number,
    noComprobable:  number,
    ambiguo:        number,
    incompleto:     number,
    identificable:  number,
    importante:     number,
    trazable:       number,
    consistente:    number,
    completo:       number,
    debil:          number,
    estable:        number,
    inestable:      number,
    correcto:       number,
    noIdentificable:number,
    noTrazable:     number,
    intrascendente: number
}